
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <h1 style = 'color : Tomato;'>PyTorch - 2 <b>(Tensors)</b></h1>
<h2>Table of content</h2>

<ol>
    <li><a href="#ref1">Introduction to tensors</a></li>
    <li><a href="#ref2">Arthematic operations with pytorch</a></li>
    <li><a href="#ref3">Matric operations with pytorch</a></li>
    
</ol>



In [35]:
import torch

<a id="ref1"></a>
<h2> Tensor Operation</h2>

In [74]:
#1D tensor 
ten1 = torch.tensor([1,2,3,4,5],dtype= torch.float64)
print(ten1)

#1D tensor with GPU
tenGPU1 = torch.tensor([1,2,3,4,5,5,6,7]).cuda()
print(tenGPU1)

tensor([1., 2., 3., 4., 5.], dtype=torch.float64)
tensor([1, 2, 3, 4, 5, 5, 6, 7], device='cuda:0')


In [87]:
#2D tensor
ten2 = torch.tensor([[2,3,4,5,6],[7,2,3,4,5,]])
print(ten2, '\n')

#2D Tensor with GPU
tenGPU2 = torch.tensor([[2,3,4,5,10],[7,2,3,4,11]]).cuda()
print(tenGPU2)


tensor([[2, 3, 4, 5, 6],
        [7, 2, 3, 4, 5]]) 

tensor([[ 2,  3,  4,  5, 10],
        [ 7,  2,  3,  4, 11]], device='cuda:0')


In [88]:
#3D Tensor
ten3 = torch.tensor([[[2,3,4,5,6],[7,2,3,4,5,]]])
print(ten3, '\n')

#3D Tensor with GPU 
tenGPU3 = torch.tensor([[[2,3,4,5,10],[7,2,3,4,11]]]).cuda()
print(tenGPU3)


tensor([[[2, 3, 4, 5, 6],
         [7, 2, 3, 4, 5]]]) 

tensor([[[ 2,  3,  4,  5, 10],
         [ 7,  2,  3,  4, 11]]], device='cuda:0')


In [70]:
#shape of above Tensors
print(ten1.shape, '\n')
print(ten2.shape, '\n')
print(ten3.shape)

torch.Size([5]) 

torch.Size([2, 5]) 

torch.Size([1, 2, 5])


In [71]:
#Shape of GPU tensor
print(tenGPU1.shape, '\n')
print(tenGPU2.shape, '\n')
print(tenGPU3.shape)

torch.Size([8]) 

torch.Size([2, 5]) 

torch.Size([1, 2, 5])


In [72]:
# Random numbers of shape 3,2
print(torch.rand(3,2), '\n')

#zeros
print(torch.zeros(3,2), '\n')

#Ones
print(torch.ones(3,2), '\n')

# Create random integers of shape(3,3)  between (0,10)
print(torch.randint(low=0, high=10, size=(3,3)))



tensor([[0.7384, 0.0126],
        [0.5293, 0.9484],
        [0.4709, 0.2496]]) 

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) 

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) 

tensor([[0, 0, 1],
        [5, 7, 6],
        [8, 6, 7]])


In [91]:
torch.range(1,10).reshape(5,2).cuda()

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]], device='cuda:0')

<a id="ref2"></a>
<h2>Arthematic operation</h2>

In [80]:
x = torch.tensor(2)
y = torch.tensor(1)
print(x,y)

tensor(2) tensor(1)


In [76]:
# addition
print(x+y)

tensor(3)


In [77]:
# subtraction
print(y-x)


tensor(-1)


In [78]:
# multiplication
print(x*y)

tensor(2)


In [81]:
# division
print(x/y)

tensor(2)


<a id="ref3"></a>
<h2>matric operation</h2>

In [82]:
a = torch.randn(3,3)
b = torch.randn(3,3)

In [85]:
# matrix addition
print(torch.add(a,b), '\n')

# matrix subtraction
print(torch.sub(a,b), '\n')

# matrix multiplication
print(torch.mm(a,b), '\n')

# matrix division
print(torch.div(a,b))

# matrix transpose
torch.t(a)

tensor([[-2.2771,  0.8774, -0.0170],
        [-1.2123, -0.0984, -2.7817],
        [ 0.2897,  2.4567,  0.6242]]) 

tensor([[ 1.5278,  4.1663, -0.2525],
        [-1.8722, -0.2486,  0.4595],
        [-1.5772,  0.6054,  1.3973]]) 

tensor([[ 1.4191,  0.6808, -4.0789],
        [ 1.7930,  1.4484,  0.5483],
        [ 2.6733,  2.1092, -2.9477]]) 

tensor([[ 0.1969, -1.5335, -1.1440],
        [-4.6742, -2.3109,  0.7165],
        [-0.6896,  1.6540, -2.6148]])


tensor([[-0.3747, -1.5422, -0.6437],
        [ 2.5219, -0.1735,  1.5311],
        [-0.1348, -1.1611,  1.0107]])